#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3
pipelines:
  branches:
    feature/*:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn clean install --file pom.xml
          after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.5.1

  custom:
     merge-to-master:
         - step:
            name: Build and Test (Master Branch)
            caches:
               - maven
            script:
              - echo "Building the master branch"
              - mvn clean install --file pom.xml
            after-script:
                # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
                - pipe: atlassian/checkstyle-report:0.3.0

     docker:
        - step:
            name: Build and Test
            script:
              - IMAGE_NAME=efundzdemo
              - docker build . --file Dockerfile --tag ${IMAGE_NAME}
              - echo "Docker image $IMAGE_NAME built successfully."
              - docker save ${IMAGE_NAME} --output "${IMAGE_NAME}.tar"
              - echo "Docker image $IMAGE_NAME saved as ${IMAGE_NAME}.tar"
            services:
              - docker
            caches:
              - docker
            artifacts:
              - "*.tar"
        - step:
            name: Push image to ECR
            script:
              - TAG_NAME=efundzdemo
              - docker build -t my-docker-image:${TAG_NAME} .
              - pipe: atlassian/aws-ecr-push-image:2.2.0
                variables:
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjEE4aCXVzLWVhc3QtMSJHMEUCIQDXwoWfZ5fYLTEHalx1FUnhqFNi1d7qJstnplMJnQNNTwIgTCAZrdYJ0B8bHPHv4Qbkp8JqsLaxlSFLBZSxA5e6K8Qq8QIINxAAGgwyNDc0MjM0NTI3ODkiDBvYlhgyrYV6ZZnh7SrOAmflpMz/oA0/ynGCjg2e0cfz9SaAjrxkaO/iVJvWggk1dmHRbgBgfVt+wuybHPjfONn9OMSu3XTgTAI+4N7YnXPC+Q9l8YabObZ5Ma3xAhV6K8CAhAKWWiNMHV5Tm7oR2h49+8BxzLx/2UyHThP6k3ufWszXtMAndvg24e2AJ8hvm/1SWIvhZMFcFPbuj9+7KgTDITMxyS7TaLd4ymsVV0rsyTe+B85nkvrNOtSM+v6poj0jqbS3HxzfCqmZEhASMSRKXrkYh6ss9owLOWJwvUwOGN87gVc0OjFW7q6i0qWAXTkyEXegch+6agQVeXYFhzD5dyJ6y+lWOLlDCxalL+KuS49anVly55yYU5kPW94nJ+G7wf9JFgFQl5QYcLug1VxjF5i+EIITurKo16rffgCKzSLUlsf/w/6HISayO36zFqZPiDL77VQoYWLAxEEw/9uIqAY6pwGvkFD4Y3zEjsP9+9RE3qmlIm36Y+rxnOWFK/qO1rtfxByPpeOBBz/TmoMuo51k8mTwQMl1LN1Va0H2n0hX0HyRARITWquuQVEuK0MANBLBIGx/71JkmupvDjvvgm/fcIeJ7aO0m3L7ar/1uttT0wvUPbDXIJ/IZVpB2gY2qBvt5dmJ/l5KKt7356NA07YnP3JCLqM31/buLaPuGupeklf5xB+oI2asgg==
                  IMAGE_NAME: ${TAG_NAME}
                  TAGS: "${BITBUCKET_BUILD_NUMBER}"
#        - step:
#            name: Push image to dockerhub
#            script:
#              - echo "${DOCKERHUB_PASSWORD}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
#              - IMAGE_NAME="efundzdemo"
#              - VERSION="dev-0.1.${BITBUCKET_BUILD_NUMBER}"
#              - IMAGE="${DOCKERHUB_NAMESPACE}/${IMAGE_NAME}:${VERSION}"
#              - docker load --input "${IMAGE_NAME}.tar"
#              - docker tag "${IMAGE_NAME}" "${IMAGE}"
#              - docker push "${IMAGE}"
#            services:
#                - docker
#        - step:
#            name: Push image to ECR
##           deployment: development
#            image: atlassian/pipelines-awscli
#            script:
#                - IMAGE_NAME="efundzdemo"
#                - VERSION="dev-0.1.${BITBUCKET_BUILD_NUMBER}"
#                - ECR_REPOSITORY="247423452789.dkr.ecr.eu-west-1.amazonaws.com/efundzz_test" # Replace with your ECR repository URL
#                - IMAGE="${ECR_REPOSITORY}:${VERSION}"
#                - echo "Installing AWS CLI..."
##                - yum update
##                - apt-get update
##                - apt-get install -y awscli
##                - export PATH=$PATH:$HOME/.local/bin
#                - echo "Logging in to AWS ECR..."
#                - export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
#                - export AWS_ACCOUNT_ID="$AWS_ACCOUNT_ID"
#                - export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
#                - export AWS_DEFAULT_REGION="$AWS_DEFAULT_REGION"
#                - echo $AWS_ACCESS_KEY_ID
#                - echo $AWS_SECRET_ACCESS_KEY
#                - echo $AWS_DEFAULT_REGION
#                - echo AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
#                - echo AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
##                - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
#                - eval $(aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com)
#                - echo "Logged in to AWS ECR"
#                - docker load < "${IMAGE_NAME}.tar"
#                - docker tag "${IMAGE_NAME}" "${IMAGE}"
#                - docker push "${IMAGE}"
#            services:
#              - docker