#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3
pipelines:
  branches:
    feature/*:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn clean install --file pom.xml
          after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.5.1
  pull-requests:
        '**':
          - step:
              name: Merge to Master
              script:
                - echo "Merging changes from branch $BITBUCKET_SOURCE_BRANCH to master"
                - git checkout master
                - git merge --no-ff $BITBUCKET_SOURCE_BRANCH
                - git push origin master
                - pipe: atlassian/pipelines-merge-action:0.3.0

        master:
         - step:
            name: Build and Test (Master Branch)
            caches:
               - maven
            script:
              - mvn clean install --file pom.xml
            after-script:
                # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
                - pipe: atlassian/checkstyle-report:0.3.0